### ISSUE TITLE
Report radio status

### ISSUE THREAD

**Issue by ke4roh** [awalls-cx18/gr-nwr#1]
For purposes of monitoring the signal and verifying continuous correct operation of the radio, output received signal strength (or some equivalent metric that can be observed to go below some threshold when the transmission disappears) and signal-to-noise ratio.  In the grand scheme, either of these numbers falling out of spec (or coming back in) will trigger an event, and they could be polled periodically to verify radio operation.

**Comment by awalls-cx18** [comment]
Solution Part 1:
Added RF Channel FM Carrier Lock detector that has output values at the audio sample rate to the nwr_fg.grc example flowgraph.  This serves as an indicator that the tuned channel has a station signal present and is at least minimally detectable.  The lock detector samples don't leave the flowgraph, but that's easy enough to do with a gr-zmq pub sink block, and the outgoing rate can easily be reduced with a keep 1 in N block (e.g. keep 1 in 16000 to get carrier lock status at an approximate 1 Hz rate although buffering delays might jitter that somewhat).

https://github.com/awalls-cx18/gr-nwr/commit/70e36ff345bd64c74156d7922c9d04fc3f114728

**Comment by awalls-cx18** [comment]
Forgot to mention, the above change necessarily required the addition of an AGC block just after the channel filter and before the carrier tracking PLL, so that a fixed lock detector threshold could be used.

**Comment by awalls-cx18** [comment]
Solution Part 2:
Added RF Channel S+N power meter that has output values at the audio sample rate to the nwr_fg.grc example flowgraph. This serves as an indicator of received signal strength from the station. 

Unfortunately, estimating noise power N, in a channel that is filtered to the signal width and with a broadcast station that is always sending a signal is problematic, as the Signal (+ Noise) power occupies the whole channel most of the time.  To properly estimate channel noise power would mean either inspecting an adjacent vacant channel and making a noise power estimate from that vacant channel, or performing audio silence detection in the channel of interest in the RF (Audio silence shows as an FM carrier only in the RF channel) and excising the carrier before estimating the noise.  That is a level of sophistication at the radio level that seems more effort than what it is worth.  The upper layers can tune the receiver to an adjacent vacant channel or monitor that adjacent channel with a stripped down receiver, and take the (S+N) estimate from the vacant channel (which is really only N) and do some algebra with the (S+N) of the channel of interest, to get S/N of the channel of interest.

The S+N samples don't leave the flowgraph, but that's easy enough to do with a gr-zmq pub sink block, and the outgoing rate can easily be reduced with a keep 1 in N block (e.g. keep 1 in 16000 to get carrier lock status at an approximate 1 Hz rate although buffering delays might jitter that somewhat).

https://github.com/awalls-cx18/gr-nwr/commit/f051d5b6c76ead1adbdb0244cc155ea806873d6d

**Comment by awalls-cx18** [comment]
BTW, using the 10 * log10(S+N) value output from the channel of interest and using the 10*log10(S+N) (which is ideally only 10 * log10(N)) value output from the adjacent vacant channel:

10 * log10(S+N) - 10 * log10(N) = 10 * log10((S+N)/N) = 10 * log10(S/N + 1) so

10^((10 * log10(S+N) - 10 * log10(N))/10) = S/N + 1  and

SNR = 10 * log10(S/N) 

The easiest way to find a vacant adjacent channel?  Look at each of WX1 through WX7 and pick the one with no lock detected with the lowest S+N reading (narrowband interferers or spurs can drive up S+N when there is no NWR broadcast present on a channel).

Closing this one as the radio controller has the means to perform this at a level above.
(Fixed formatting)

**Comment by ke4roh** [comment]
Thanks, and thanks for the detailed answers here!

**Comment by awalls-cx18** [comment]
YW.

FWIW, the Si4707 provides SNR for Audio (for sure)  and RSSI for the RF channel (I think).

The 10 * log10(S+N) output value in the example flowgraph is an RSSI for the RF channel (before FM demodulation).
